site_name: ParsBench Documentation
site_description: ParsBench provides toolkits for benchmarking LLMs based on the Persian language.
site_author: Shahriar Shariati

repo_url: https://github.com/shahriarshm/parsbench
remote_branch: main
repo_name: parsbench

theme:
  name: material
  logo: imgs/logo-black.svg
  favicon: imgs/logo.svg
  palette:
    primary: white
    accent: teal

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - attr_list
  - tables
  - pymdownx.highlight
  - pymdownx.superfences

nav:
    - Overview: index.md
    - Getting Started: getting-started.md
    - Tutorial:
      - Models: tutorial/models.md
      - Tasks: tutorial/tasks.md
      - Benchmarks: tutorial/benchmarks.md
      - Advanced: tutorial/advanced.md
    - Contribution: contribution.md
    - Code Reference:
        - Models: code_reference/models.md
        - Scores: code_reference/scores.md
        - Tasks: code_reference/tasks.md
        - Benchmarks: code_reference/benchmarks.md
    - Changelog: changelog.md
